"""
utils/pdf_report.py
PDF report generation using ReportLab.
Generates: student receipts, monthly reports, P&L statements.
"""
from io import BytesIO
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table,
    TableStyle, HRFlowable,
)
from reportlab.lib.enums import TA_CENTER, TA_RIGHT

from modules.config import APP_TITLE, CURRENCY, CURRENCY_CODE


# ── Colour palette ──────────────────────────────────────────────────────────
BLUE   = colors.HexColor("#2563EB")
GRAY   = colors.HexColor("#6B7280")
LIGHT  = colors.HexColor("#EFF6FF")
WHITE  = colors.white
BLACK  = colors.black


def _base_doc(buf: BytesIO, title: str) -> SimpleDocTemplate:
    return SimpleDocTemplate(
        buf, pagesize=A4,
        rightMargin=2*cm, leftMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm,
        title=title, author=APP_TITLE,
    )


def _header_para(text: str, styles) -> Paragraph:
    s = ParagraphStyle("hdr", parent=styles["Title"],
                        textColor=BLUE, fontSize=20, spaceAfter=4)
    return Paragraph(text, s)


def _sub_para(text: str, styles) -> Paragraph:
    s = ParagraphStyle("sub", parent=styles["Normal"],
                        textColor=GRAY, fontSize=10)
    return Paragraph(text, s)


# ── Receipt ──────────────────────────────────────────────────────────────────

def generate_receipt(data: dict) -> bytes:
    """
    data keys: student_id, name, course, amount, date, note
    Returns PDF bytes.
    """
    buf    = BytesIO()
    doc    = _base_doc(buf, "Payment Receipt")
    styles = getSampleStyleSheet()
    story  = []

    # Header
    story.append(_header_para(f"🏦 {APP_TITLE}", styles))
    story.append(_sub_para("Payment Receipt", styles))
    story.append(Spacer(1, 0.4*cm))
    story.append(HRFlowable(width="100%", thickness=1, color=BLUE))
    story.append(Spacer(1, 0.4*cm))

    # Receipt details table
    receipt_no = f"RCP-{datetime.now().strftime('%Y%m%d%H%M%S')}"
    table_data = [
        ["Receipt No.",  receipt_no,             "Date", data.get("date", "")],
        ["Student ID",   data.get("student_id",""), "Course", data.get("course", "")],
        ["Student Name", data.get("name", ""),   "",       ""],
    ]
    t = Table(table_data, colWidths=[3.5*cm, 6*cm, 3*cm, 5*cm])
    t.setStyle(TableStyle([
        ("FONTNAME",  (0,0), (-1,-1), "Helvetica"),
        ("FONTSIZE",  (0,0), (-1,-1), 9),
        ("TEXTCOLOR", (0,0), (0,-1), GRAY),
        ("TEXTCOLOR", (2,0), (2,-1), GRAY),
        ("BACKGROUND",(0,0), (-1,0), LIGHT),
        ("ROWBACKGROUNDS", (0,0), (-1,-1), [WHITE, LIGHT]),
        ("BOX", (0,0), (-1,-1), 0.5, GRAY),
        ("INNERGRID", (0,0), (-1,-1), 0.25, GRAY),
        ("PADDING", (0,0), (-1,-1), 5),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.5*cm))

    # Amount box
    amount = data.get("amount", 0)
    amount_table = Table(
        [[f"Amount Paid", f"{CURRENCY}{amount:,.0f}"]],
        colWidths=[9*cm, 8*cm],
    )
    amount_table.setStyle(TableStyle([
        ("FONTNAME",   (0,0), (-1,-1), "Helvetica-Bold"),
        ("FONTSIZE",   (0,0), (0,0), 11),
        ("FONTSIZE",   (1,0), (1,0), 18),
        ("TEXTCOLOR",  (1,0), (1,0), BLUE),
        ("BACKGROUND", (0,0), (-1,-1), LIGHT),
        ("BOX",        (0,0), (-1,-1), 1, BLUE),
        ("PADDING",    (0,0), (-1,-1), 12),
        ("ALIGN",      (1,0), (1,0), "RIGHT"),
    ]))
    story.append(amount_table)

    if data.get("note"):
        story.append(Spacer(1, 0.3*cm))
        story.append(_sub_para(f"Note: {data['note']}", styles))

    story.append(Spacer(1, 1*cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=GRAY))
    story.append(Spacer(1, 0.2*cm))

    footer = ParagraphStyle("footer", parent=styles["Normal"],
                             fontSize=8, textColor=GRAY, alignment=TA_CENTER)
    story.append(Paragraph(f"Generated by {APP_TITLE} · {datetime.now().strftime('%Y-%m-%d %H:%M')}", footer))
    story.append(Paragraph("This is a computer-generated receipt and does not require a signature.", footer))

    doc.build(story)
    return buf.getvalue()


# ── Monthly Report ────────────────────────────────────────────────────────────

def generate_monthly_report(summary: dict, expense_grp, revenue_grp, month: str) -> bytes:
    """
    summary: dict from utils/finance.monthly_summary
    expense_grp, revenue_grp: DataFrames from expense_breakdown / revenue_breakdown
    """
    buf    = BytesIO()
    doc    = _base_doc(buf, f"Monthly Report — {month}")
    styles = getSampleStyleSheet()
    story  = []

    story.append(_header_para(f"🏦 {APP_TITLE}", styles))
    story.append(_sub_para(f"Monthly Finance Report — {month}", styles))
    story.append(Spacer(1, 0.3*cm))
    story.append(HRFlowable(width="100%", thickness=1, color=BLUE))
    story.append(Spacer(1, 0.4*cm))

    # KPI summary
    h = ParagraphStyle("h2", parent=styles["Heading2"], textColor=BLUE)
    story.append(Paragraph("Summary", h))
    story.append(Spacer(1, 0.2*cm))

    kpi_data = [
        ["Metric", "Amount"],
        ["Total Revenue",  f"{CURRENCY}{summary['total_revenue']:,.2f}"],
        ["Total Expenses", f"{CURRENCY}{summary['total_expenses']:,.2f}"],
        ["Net Profit",     f"{CURRENCY}{summary['net_profit']:,.2f}"],
        ["Profit Margin",  f"{summary['profit_margin']:.1f}%"],
    ]
    kpi_t = Table(kpi_data, colWidths=[9*cm, 8*cm])
    kpi_t.setStyle(TableStyle([
        ("FONTNAME",    (0,0), (-1,0),  "Helvetica-Bold"),
        ("BACKGROUND",  (0,0), (-1,0),  BLUE),
        ("TEXTCOLOR",   (0,0), (-1,0),  WHITE),
        ("FONTNAME",    (0,-1),(-1,-1), "Helvetica-Bold"),
        ("TEXTCOLOR",   (0,-1),(-1,-1), BLUE),
        ("ROWBACKGROUNDS",(0,1),(-1,-1),[WHITE, LIGHT]),
        ("BOX",         (0,0), (-1,-1), 0.5, GRAY),
        ("INNERGRID",   (0,0), (-1,-1), 0.25, GRAY),
        ("PADDING",     (0,0), (-1,-1), 7),
        ("ALIGN",       (1,0), (1,-1),  "RIGHT"),
    ]))
    story.append(kpi_t)
    story.append(Spacer(1, 0.6*cm))

    # Expense breakdown
    if expense_grp is not None and not expense_grp.empty:
        story.append(Paragraph("Expense Breakdown", h))
        story.append(Spacer(1, 0.2*cm))
        exp_data = [["Category", "Amount", "%"]]
        for _, row in expense_grp.iterrows():
            exp_data.append([row["Category"], f"{CURRENCY}{row['Amount']:,.0f}", f"{row['Percentage']}%"])
        exp_t = Table(exp_data, colWidths=[9*cm, 6*cm, 2.5*cm])
        exp_t.setStyle(TableStyle([
            ("FONTNAME",   (0,0), (-1,0), "Helvetica-Bold"),
            ("BACKGROUND", (0,0), (-1,0), BLUE),
            ("TEXTCOLOR",  (0,0), (-1,0), WHITE),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[WHITE, LIGHT]),
            ("BOX",        (0,0), (-1,-1), 0.5, GRAY),
            ("INNERGRID",  (0,0), (-1,-1), 0.25, GRAY),
            ("PADDING",    (0,0), (-1,-1), 6),
            ("ALIGN",      (1,1), (-1,-1), "RIGHT"),
        ]))
        story.append(exp_t)
        story.append(Spacer(1, 0.6*cm))

    # Footer
    story.append(HRFlowable(width="100%", thickness=0.5, color=GRAY))
    footer_style = ParagraphStyle("footer", parent=styles["Normal"],
                                   fontSize=8, textColor=GRAY, alignment=TA_CENTER)
    from datetime import datetime as dt
    story.append(Paragraph(
        f"Generated by {APP_TITLE} · {dt.now().strftime('%Y-%m-%d %H:%M')} · Confidential",
        footer_style,
    ))

    doc.build(story)
    return buf.getvalue()
